# Generated by Django 2.2.5 on 2019-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='point',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Team',
            new_name='team',
        ),
    ]
