# Generated by Django 2.2.3 on 2019-09-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190916_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assist_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='block_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nba_team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='point_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebound_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='steal_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='threepointer_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='turnover_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_assists',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_blocks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_rebounds',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_steals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_threepointers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_turnovers',
            field=models.IntegerField(blank=True),
        ),
    ]
