# Generated by Django 2.2.5 on 2019-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_team_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
